### ISSUE TITLE
Columns are stretched in IE 11

### ISSUE THREAD

**Issue by romamilkovic** [matthewsimo/scss-flex-grid#10]
Hello Matthew, you did a really great work, thank you for that.

But, unfortunately, I have a problem when testing my site in IE 11(0.8).

Here is a code http://codepen.io/romamilkovic/full/zrOdvL/

And screenshot from the browser. 
![bug](https://cloud.githubusercontent.com/assets/10686894/11531010/77ab49de-9934-11e5-9adc-752aea9a8f46.png)

I hope you help me to solve this problem. Thanks!

**Comment by matthewsimo** [comment]
Hello @romamilkovic - thanks for the kind words and giving my little grid a shot. Thank you for included your code, that was very helpful  -- I see you are using autoprefixer, good.

Unfortunately, I don't have access to IE11 right now but can take a look tonight some. In the meantime I'd suggest looking at either:

- adjusting `flex-basis` ( IE11 has funny defaults )
- setting a specific `height` for your flex items ( `min-height` looks like it isn't respected if `display: flex` and `flex-direction: column` are defined.. )

Though, I'm only guessing based on info from the "Known Issues" tab here: http://caniuse.com/#feat=flexbox

If you do find out a solution, please let me know - I'd like to make sure IE11 is properly supported.

**Comment by romamilkovic** [comment]
@matthewsimo Thanks for your quick reply, really appreciated it. 

I fixed this bug by adding min-height: 1px; to all child element. 

It's not your fault, this is a Microsoft mistake. ;)

Thanks!

**Comment by matthewsimo** [comment]
Great, glad you found a good solution!

**Comment by mstrutt** [comment]
`min-height: 1px;` worked for me too, thanks for posting your fix here @romamilkovic

**Comment by matthewsimo** [comment]
I added this fix to columns in `0.3.4`, thanks!
