### ISSUE TITLE
Remove gutters on outside

### ISSUE THREAD

**Issue by timdiacon** [matthewsimo/scss-flex-grid#15]
Would be great to have an option to remove gutters on the outside of the grid. I want the content of the first and last columns to touch the edge of the browser viewport.

Currently it does this but it means you get a horizontal scrollbar on the page. If you set padding to eliminate the scroll bar as suggested in other issues then the gutters of those columns bring the content in from the edge of the page.

**Comment by timdiacon** [comment]
realised actually you could just add `overflow-x: hidden;` to the parent container. Maybe a bit hacky but works :-)

**Comment by matthewsimo** [comment]
I've thought about this some more and have decided that I think it should be handled in the site's specific styles which is easy enough to target. Thanks for the suggestion.
