### ISSUE TITLE
_flex-grid.scss

### ISSUE THREAD

**Issue by crispinh2o** [matthewsimo/scss-flex-grid#6]
Hi, I like your work!! :+1: 

Only one thing... the variable **$fg-breakpoints** (line 41 _flex-grid.scss) not defined the size of pixels for sm..

$fg-breakpoints: (
  (xs),
  (sm, 768**px**),
  (md, 992px),
  (lg, 1200px)
) !default;

I wait your answer,

BR, Thank you!

**Comment by matthewsimo** [comment]
Thanks for catching this - I've updated it to include the units.

**Comment by crispinh2o** [comment]
: )
